FROM eclipse-temurin:21-jdk-alpine
VOLUME /tmp
EXPOSE 9142
ADD ./kube-api-service/target/*.jar /app.jar
RUN apk update && apk add curl
EXPOSE 8080
EXPOSE 8081
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]
