FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
VOLUME /tmp
EXPOSE 8080 8081 9142
ADD ./kube-api-service/target/*.jar app.jar
RUN apk add --no-cache curl
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]
