apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-reader
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
